### ISSUE TITLE
prander fails while processing section [.text]

### ISSUE THREAD

**Issue by RSAkidinUSA** [kevinkoo001/CCR#3]
Attempting to run prander.py on the funcptr example (or any other binary compiled with CCR on my system) breaks with the following error:

```
rburrow@ics-dev:~/CCR$ python randomizer/prander.py -s ./examples/funcptr

    ___   ___   __         ___                     _
   / __\ / __\ /__\       / _ \_ __ __ _ _ __   __| | ___ _ __
  / /   / /   / \//_____ / /_)/ '__/ _` | '_ \ / _` |/ _ \ '__|
 / /___/ /___/ _  \_____/ ___/| | | (_| | | | | (_| |  __/ |
 \____/\____/\/ \_/     \/    |_|  \__,_|_| |_|\__,_|\___|_/

 Compiler-assisted Code Randomization: Practical Randomizer
 (In the 39th IEEE Symposium on Security & Privacy 2018)

2019-10-29 14:31:18,779 [INFO   ] Reading the metadata from the .rand section... (shuffleInfoReader.py:164)
2019-10-29 14:31:18,780 [INFO   ]       Offset to the object  : 0xf0 (shuffleInfoReader.py:165)
2019-10-29 14:31:18,780 [INFO   ]       Offset to the main()  : 0x20 (shuffleInfoReader.py:166)
2019-10-29 14:31:18,781 [INFO   ]       Total Emitted Bytes   : 0x0310 (shuffleInfoReader.py:167)
2019-10-29 14:31:18,781 [INFO   ]       Number of Objects     : 1 (shuffleInfoReader.py:168)
2019-10-29 14:31:18,781 [INFO   ]       Number of Functions   : 9 (shuffleInfoReader.py:169)
2019-10-29 14:31:18,781 [INFO   ]       Number of Basic Blocks: 32 (shuffleInfoReader.py:170)
2019-10-29 14:31:18,782 [INFO   ]       Fixups in .text : 56  (shuffleInfoReader.py:56)
2019-10-29 14:31:18,782 [INFO   ]       Fixups in .rodata       : 18  (shuffleInfoReader.py:56)
2019-10-29 14:31:18,783 [INFO   ]       Fixups in .data : 4  (shuffleInfoReader.py:56)
2019-10-29 14:31:18,783 [INFO   ]       Number of Jump Tables : 1 (shuffleInfoReader.py:200)
2019-10-29 14:31:18,784 [INFO   ] Building up the layout... (prander.py:43)
                                        100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2019-10-29 14:31:18,801 [INFO   ] Sanity check for ./examples/funcptr...  (reorderInfo.py:593)
2019-10-29 14:31:18,801 [INFO   ]       All sanity checks have been PASSED!! (reorderInfo.py:618)
2019-10-29 14:31:18,802 [INFO   ] Performing reordering (@FUN)... (prander.py:48)
2019-10-29 14:31:18,802 [INFO   ]       # of Function Constraints: 0 (reorderEngine.py:236)
2019-10-29 14:31:18,803 [INFO   ] Instrumenting the binary... (prander.py:66)
2019-10-29 14:31:18,805 [INFO   ]       Processing section [.dynsym] (binaryBuilder.py:841)
                                        100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2019-10-29 14:31:18,810 [INFO   ]       Processing section [.rela.dyn] (binaryBuilder.py:841)
2019-10-29 14:31:18,813 [INFO   ]       Processing section [.text] (binaryBuilder.py:841)
Traceback (most recent call last):
  File "randomizer/prander.py", line 161, in <module>
    transformBinary(fp, opts, R, granularity=granularity, showlevel=4)
  File "randomizer/prander.py", line 89, in transformBinary
    transformBinaryImpl(target, opts, C.METADATA_PATH, granularity, R, hasRandSection=True, showlevel=showlevel)
  File "randomizer/prander.py", line 71, in transformBinaryImpl
    BB.instrumentBin(oldBin, newBin, isSymbolUpdate)
  File "/home/rburrow/CCR/randomizer/binaryBuilder.py", line 848, in instrumentBin
    self.patchCodeSection(sectionChunk)
  File "/home/rburrow/CCR/randomizer/binaryBuilder.py", line 163, in patchCodeSection
    self.instBin += self.PK(FMT.INT, mainBBL.newVA)
AttributeError: 'NoneType' object has no attribute 'newVA'
```

It appears a call to getBBlByVA() does not return any value if the VA provided is not in the dictionary and that is not being handled.

I am running this on Ubuntu 18.04.1 and had no problems building ccr or compiling the binaries themselves.

**Comment by kevinkoo001** [comment]
Hi Ryan, thanks for your interest in CCR.
Have you tried to run it under Ubuntu 16.04? Which LLVM version have you compiled? I'll take a look.

**Comment by kevinkoo001** [comment]
Okay, it happens due to different implementation of one of CRT functions - `crt1.o` that defines `_start()`. It is automatically linked to the main executable at link time unless specified. When updating the location of a user-defined function `main()`, `prander` internally assumes the 4 bytes is an absolute address to patch. However,  the `_start()` implementation in Ubuntu 18.04 uses a rip-relative address that leads to fail the location of `main()` function. The following (*) shows how `_start` in `crt1.o` looks different between Ubuntu 16.04 and 18.04.

```
<_start> in Ubuntu 16.04:
d:	50                   	push   %rax
e:	54                   	push   %rsp
f:	49 c7 c0 00 00 00 00 	mov    $0x0,%r8
16:	48 c7 c1 00 00 00 00 	mov    $0x0,%rcx
1d:	48 c7 c7 00 00 00 00 	mov    $0x0,%rdi (*)
24:	e8 00 00 00 00       	callq  29 <_start+0x29>

<_start> in Ubuntu 18.04:
d:   50                       push   %rax
e:   54                       push   %rsp
f:   4c 8b 05 00 00 00 00     mov    0x0(%rip),%r8     # 16 <_start+0x16>
16:   48 8b 0d 00 00 00 00    mov    0x0(%rip),%rcx    # 1d <_start+0x1d>
1d:   48 8b 3d 00 00 00 00    mov    0x0(%rip),%rdi    # 24 <_start+0x24> (*)
24:   ff 15 00 00 00 00       callq  *0x0(%rip)        # 2a <_start+0x2a>
```

I have fixed it so let me know if it's working.

**Comment by RSAkidinUSA** [comment]
Yup that looks like it was the problem! Thanks!
