### ISSUE TITLE
Building shared libraries

### ISSUE THREAD

**Issue by tpottei1** [kevinkoo001/CCR#5]
Hi, this seems like a neat tool. I have seen similar tools like multicompiler and was interested in testing it out. I did a quick test with nginx and was able to use prander with the nginx executable itself. But, I tried on some corresponding shared libraries ngx_http_geoip_module.so, ngx_http_image_filter_module.so, and ngx_http_xslt_filter_module.so but saw a mismatch in the instrumented file size and the original file size and could not shuffle the shared libraries. Are there specific command line flags I have to provide to prander or ccr for shared libraries?

tpottei1@tpottei1-ThinkPad-E570:~/source-packages/ng_source/nginx-1.14.0/debian/build-extras/objs$ readelf -SW ngx_http_geoip_module.so | grep rand
  [35] .rand             PROGBITS        0000000000000000 014b1c 000515 00      0   0  1
tpottei1@tpottei1-ThinkPad-E570:~/source-packages/ng_source/nginx-1.14.0/debian/build-extras/objs$ python /home/tpottei1/CCR/randomizer/prander.py /home/tpottei1/source-packages/ng_source/nginx-1.14.0/debian/build-extras/objs/ngx_http_image_filter_module.so

    ___   ___   __         ___                     _
   / __\ / __\ /__\       / _ \_ __ __ _ _ __   __| | ___ _ __
  / /   / /   / \//_____ / /_)/ '__/ _` | '_ \ / _` |/ _ \ '__|
 / /___/ /___/ _  \_____/ ___/| | | (_| | | | | (_| |  __/ |
 \____/\____/\/ \_/     \/    |_|  \__,_|_| |_|\__,_|\___|_/

 Compiler-assisted Code Randomization: Practical Randomizer
 (In the 39th IEEE Symposium on Security & Privacy 2018)

2020-05-28 01:15:58,962 [INFO   ] Reading the metadata from the .rand section... (shuffleInfoReader.py:164)
2020-05-28 01:15:58,962 [INFO   ] 	Offset to the object  : 0xe0 (shuffleInfoReader.py:165)
2020-05-28 01:15:58,962 [INFO   ] 	Offset to the main()  : 0x00 (shuffleInfoReader.py:166)
2020-05-28 01:15:58,962 [INFO   ] 	Total Emitted Bytes   : 0x21d0 (shuffleInfoReader.py:167)
2020-05-28 01:15:58,962 [INFO   ] 	Number of Objects     : 1 (shuffleInfoReader.py:168)
2020-05-28 01:15:58,962 [INFO   ] 	Number of Functions   : 11 (shuffleInfoReader.py:169)
2020-05-28 01:15:58,962 [INFO   ] 	Number of Basic Blocks: 447 (shuffleInfoReader.py:170)
2020-05-28 01:15:58,964 [INFO   ] 	Fixups in .text	: 573  (shuffleInfoReader.py:56)
2020-05-28 01:15:58,964 [INFO   ] 	Fixups in .rodata	: 16  (shuffleInfoReader.py:56)
2020-05-28 01:15:58,964 [INFO   ] 	Fixups in .data	: 50  (shuffleInfoReader.py:56)
2020-05-28 01:15:58,964 [INFO   ] 	Fixups in .data.rel.ro	: 4  (shuffleInfoReader.py:56)
2020-05-28 01:15:58,965 [INFO   ] 	Number of Jump Tables : 4 (shuffleInfoReader.py:200)
2020-05-28 01:15:58,966 [INFO   ] Building up the layout... (prander.py:43)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2020-05-28 01:15:58,979 [INFO   ] Sanity check for /home/tpottei1/source-packages/ng_source/nginx-1.14.0/debian/build-extras/objs/ngx_http_image_filter_module.so...  (reorderInfo.py:593)
2020-05-28 01:15:58,980 [INFO   ] 	All sanity checks have been PASSED!! (reorderInfo.py:618)
2020-05-28 01:15:58,980 [INFO   ] Performing reordering (@FUN)... (prander.py:48)
2020-05-28 01:15:58,980 [INFO   ] 	# of Function Constraints: 0 (reorderEngine.py:236)
2020-05-28 01:15:58,982 [INFO   ] Instrumenting the binary... (prander.py:66)
2020-05-28 01:15:58,983 [INFO   ] 	Processing section [.dynsym] (binaryBuilder.py:875)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2020-05-28 01:15:58,990 [INFO   ] 	Processing section [.rela.dyn] (binaryBuilder.py:875)
2020-05-28 01:15:59,037 [INFO   ] 	Processing section [.text] (binaryBuilder.py:875)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2020-05-28 01:15:59,040 [INFO   ] 	Processing section [.rodata] (binaryBuilder.py:875)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2020-05-28 01:15:59,041 [INFO   ] 	Processing section [.eh_frame] (binaryBuilder.py:875)
2020-05-28 01:15:59,046 [INFO   ] 	Processing section [.eh_frame_hdr] (binaryBuilder.py:875)
2020-05-28 01:15:59,052 [INFO   ] 	Processing section [.init_array] (binaryBuilder.py:875)
2020-05-28 01:15:59,052 [INFO   ] 	Processing section [.data.rel.ro] (binaryBuilder.py:875)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
2020-05-28 01:15:59,052 [INFO   ] 	Processing section [.data] (binaryBuilder.py:875)
					100% [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
Traceback (most recent call last):
  File "/home/tpottei1/goCCR/CCR3/CCR/randomizer/prander.py", line 161, in <module>
    transformBinary(fp, opts, R, granularity=granularity, showlevel=4)
  File "/home/tpottei1/goCCR/CCR3/CCR/randomizer/prander.py", line 89, in transformBinary
    transformBinaryImpl(target, opts, C.METADATA_PATH, granularity, R, hasRandSection=True, showlevel=showlevel)
  File "/home/tpottei1/goCCR/CCR3/CCR/randomizer/prander.py", line 71, in transformBinaryImpl
    BB.instrumentBin(oldBin, newBin, isSymbolUpdate)
  File "/home/tpottei1/goCCR/CCR3/CCR/randomizer/binaryBuilder.py", line 928, in instrumentBin
    (layoutName, start, end, end - start, len(self.instBin))
AssertionError: Size Mismatch (.debug_info): Orig[0xc61c:0x1483d] SecSz:33313B InstBinSz: 361764B

**Comment by kevinkoo001** [comment]
Hi thanks for your interest in CCR. The error message says the size of the last processing section was not matched during binary instrumentation. The `._debug_*` sections are experimental. Can you give it try on a stripped binary?

**Comment by tpottei1** [comment]
That did the trick! Thanks so much for the quick reply!
